
country_codes_and_html = {'AED': 1583,
 'AFN' : 65,
 'ALL' : 76,
 'AMD' : 1423,
 'ANG' : 402,
 'AOA' : 75,
 'ARS' : 36,
 'AUD' : 36,
 'AWG' : 402,
 'AZN' : 1084,
 'BAM' : 75,
 'BBD' : 36,
 'BDT' : 2547,
 'BGN' : 1083,
 'BHD' : 1583,
 'BIF' : 70,
 'BMD' : 36,
 'BND' : 36,
 'BOB' : 36,
 'BRL' : 82,
 'BSD' : 36,
 'BTN' : 78,
 'BWP' : 80,
 'BYR' : 112,
 'BZD' : 66,
 'CAD' : 36,
 'CDF' : 70,
 'CHF' : 67,
 'CLF' : 152,
 'CLP' : 36,
 'CNY' : 165,
 'COP' : 36,
 'CRC' : 8353,
 'CUP' : 8396,
 'CVE' : 36,
 'CZK' : 75,
 'DJF' : 70,
 'DKK' : 107,
 'DOP' : 82,
 'DZD' : 1583,
 'EGP' : 163,
 'ETB' : 66,
 'EUR' : 8364,
 'FJD' : 36,
 'FKP' : 163,
 'GBP' : 163,
 'GEL' : 4314,
 'GHS' : 162,
 'GIP' : 163,
 'GMD' : 68,
 'GNF' : 70,
 'GTQ' : 81,
 'GYD' : 36,
 'HKD' : 36,
 'HNL' : 76,
 'HRK' : 107,
 'HTG' : 71,
 'HUF' : 70,
 'IDR' : 82,
 'ILS' : 8362,
 'INR' : 8377,
 'IQD' : 1593,
 'IRR' : 65020,
 'ISK' : 107,
 'JEP' : 163,
 'JMD' : 74,
 'JOD' : 74,
 'JPY' : 165,
 'KES' : 75,
 'KGS' : 1083,
 'KHR' : 6107,
 'KMF' : 67,
 'KPW' : 8361,
 'KRW' : 8361,
 'KWD' : 1583,
 'KYD' : 36,
 'KZT' : 1083,
 'LAK' : 8365,
 'LBP' : 163,
 'LKR' : 8360,
 'LRD' : 36,
 'LSL' : 76,
 'LTL' : 76,
 'LVL' : 76,
 'LYD' : 1604,
 'MAD' : 1583,
 'MDL' : 76,
 'MGA' : 65,
 'MKD' : 1076,
 'MMK' : 75,
 'MNT' : 8366,
 'MOP' : 77,
 'MRO' : 85,
 'MUR' : 8360,
 'MVR' : 1923,
 'MWK' : 77,
 'MXN' : 36,
 'MYR' : 82,
 'MZN' : 77,
 'NAD' : 36,
 'NGN' : 8358,
 'NIO' : 67,
 'NOK' : 107,
 'NPR' : 8360,
 'NZD' : 36,
 'OMR' : 65020,
 'PAB' : 66,
 'PEN' : 83,
 'PGK' : 75,
 'PHP' : 8369,
 'PKR' : 8360,
 'PLN' : 122,
 'PYG' : 71,
 'QAR' : 65020,
 'RON' : 108,
 'RSD' : 1044,
 'RUB' : 1088,
 'RWF' : 1585,
 'SAR' : 65020,
 'SBD' : 36,
 'SCR' : 8360,
 'SDG' : 163,
 'SEK' : 107,
 'SGD' : 36,
 'SHP' : 163,
 'SLL' : 76,
 'SOS' : 83,
 'SRD' : 36,
 'STD' : 68,
 'SVC' : 36,
 'SYP' : 163,
 'SZL' : 76,
 'THB' : 3647,
 'TJS' : 84,
 'TMT' : 109,
 'TND' : 1583,
 'TOP' : 84,
 'TRY' : 8356,
 'TTD' : 36,
 'TWD' : 78,
 'TZS' : 834,
 'UAH' : 8372,
 'UGX' : 85,
 'USD' : 36,
 'UYU' : 36,
 'UZS' : 1083,
 'VEF' : 66,
 'VND' : 8363,
 'VUV' : 86,
 'WST' : 87,
 'XAF' : 70,
 'XCD' : 36,
 'XDR' : 960,
 'XOF' : 952,
 'XPF' : 70,
 'YER' : 65020,
 'ZAR' : 82,
 'ZMK' : 90,
 'ZWL' : 90}

country_and_currency_codes = {'Afghanistan': 'AFN',
 'Akrotiri and Dhekelia': 'EUR',
 'Aland Islands': 'EUR',
 'Albania': 'ALL',
 'Algeria': 'DZD',
 'American Samoa': 'USD',
 'Andorra': 'EUR',
 'Angola': 'AOA',
 'Anguilla': 'XCD',
 'Antigua and Barbuda': 'XCD',
 'Argentina': 'ARS',
 'Armenia': 'AMD',
 'Aruba': 'AWG',
 'Ascension Island': 'SHP',
 'Australia': 'AUD',
 'Austria': 'EUR',
 'Azerbaijan': 'AZN',
 'Bahamas': 'BSD',
 'Bahrain': 'BHD',
 'Bangladesh': 'BDT',
 'Barbados': 'BBD',
 'Belarus': 'BYN',
 'Belgium': 'EUR',
 'Belize': 'BZD',
 'Benin': 'XOF',
 'Bermuda': 'BMD',
 'Bhutan': 'BTN',
 'Bolivia': 'BOB',
 'Bonaire': 'USD',
 'Bosnia and Herzegovina': 'BAM',
 'Botswana': 'BWP',
 'Brazil': 'BRL',
 'British Indian Ocean Territory': 'USD',
 'British Virgin Islands': 'USD',
 'Brunei': 'BND',
 'Bulgaria': 'BGN',
 'Burkina Faso': 'XOF',
 'Burundi': 'BIF',
 'Cabo Verde': 'CVE',
 'Cambodia': 'KHR',
 'Cameroon': 'XAF',
 'Canada': 'CAD',
 'Caribbean Netherlands': 'USD',
 'Cayman Islands': 'KYD',
 'Central African Republic': 'XAF',
 'Chad': 'XAF',
 'Chatham Islands': 'NZD',
 'Chile': 'CLP',
 'China': 'CNY',
 'Christmas Island': 'AUD',
 'Cocos (Keeling) Islands': 'AUD',
 'Colombia': 'COP',
 'Comoros': 'KMF',
 'Congo': 'CDF',
 'Cook Islands': 'none',
 'Costa Rica': 'CRC',
 "Cote d'Ivoire": 'XOF',
 'Croatia': 'EUR',
 'Cuba': 'CUP',
 'Curacao': 'ANG',
 'Cyprus': 'EUR',
 'Czechia': 'CZK',
 'Denmark': 'DKK',
 'Djibouti': 'DJF',
 'Dominica': 'XCD',
 'Dominican Republic': 'DOP',
 'Ecuador': 'USD',
 'Egypt': 'EGP',
 'El Salvador': 'USD',
 'Equatorial Guinea': 'XAF',
 'Eritrea': 'ERN',
 'Estonia': 'EUR',
 'Eswatini': 'SZL',
 'Ethiopia': 'ETB',
 'Falkland Islands': 'FKP',
 'Faroe Islands': 'none',
 'Fiji': 'FJD',
 'Finland': 'EUR',
 'France': 'EUR',
 'French GuianaÂ\xa0': 'EUR',
 'French PolynesiaÂ\xa0': 'XPF',
 'Gabon': 'XAF',
 'Gambia': 'GMD',
 'Georgia': 'GEL',
 'Germany': 'EUR',
 'Ghana': 'GHS',
 'Gibraltar': 'GIP',
 'Greece': 'EUR',
 'Greenland': 'DKK',
 'Grenada': 'XCD',
 'GuadeloupeÂ\xa0': 'EUR',
 'GuamÂ\xa0': 'USD',
 'Guatemala': 'GTQ',
 'Guernsey': 'GGP',
 'Guinea': 'GNF',
 'Guinea-Bissau': 'XOF',
 'Guyana': 'GYD',
 'Haiti': 'HTG',
 'Honduras': 'HNL',
 'Hong Kong': 'HKD',
 'Hungary': 'HUF',
 'Iceland': 'ISK',
 'India': 'INR',
 'Indonesia': 'IDR',
 'International Monetary Fund (IMF)': 'XDR',
 'Iran': 'IRR',
 'Iraq': 'IQD',
 'Ireland': 'EUR',
 'Isle of ManÂ\xa0': 'IMP',
 'Israel': 'ILS',
 'Italy': 'EUR',
 'Jamaica': 'JMD',
 'Japan': 'JPY',
 'JerseyÂ\xa0': 'JEP',
 'Jordan': 'JOD',
 'Kazakhstan': 'KZT',
 'Kenya': 'KES',
 'Kiribati': 'AUD',
 'Kosovo': 'EUR',
 'Kuwait': 'KWD',
 'Kyrgyzstan': 'KGS',
 'Laos': 'LAK',
 'Latvia': 'EUR',
 'Lebanon': 'LBP',
 'Lesotho': 'LSL',
 'Liberia': 'LRD',
 'Libya': 'LYD',
 'Liechtenstein': 'CHF',
 'Lithuania': 'EUR',
 'Luxembourg': 'EUR',
 'MacauÂ\xa0': 'MOP',
 'Madagascar': 'MGA',
 'Malawi': 'MWK',
 'Malaysia': 'MYR',
 'Maldives': 'MVR',
 'Mali': 'XOF',
 'Malta': 'EUR',
 'Marshall Islands': 'USD',
 'MartiniqueÂ\xa0': 'EUR',
 'Mauritania': 'MRU',
 'Mauritius': 'MUR',
 'Mayotte': 'EUR',
 'Mexico': 'MXN',
 'Micronesia': 'USD',
 'Moldova': 'MDL',
 'Monaco': 'EUR',
 'Mongolia': 'MNT',
 'Montenegro': 'EUR',
 'Montserrat': 'XCD',
 'Morocco': 'MAD',
 'Mozambique': 'MZN',
 'Myanmar': 'MMK',
 'Namibia': 'NAD',
 'Nauru': 'AUD',
 'Nepal': 'NPR',
 'Netherlands': 'EUR',
 'New CaledoniaÂ\xa0': 'XPF',
 'New Zealand': 'NZD',
 'Nicaragua': 'NIO',
 'Niger': 'XOF',
 'Nigeria': 'NGN',
 'NiueÂ\xa0': 'NZD',
 'Norfolk Island': 'AUD',
 'Northern Mariana Islands': 'USD',
 'North Korea': 'KPW',
 'North Macedonia': 'MKD',
 'Norway': 'NOK',
 'Oman': 'OMR',
 'Pakistan': 'PKR',
 'Palau': 'USD',
 'Palestine': 'ILS',
 'Panama': 'USD',
 'Papua New Guinea': 'PGK',
 'Paraguay': 'PYG',
 'Peru': 'PEN',
 'Philippines': 'PHP',
 'Pitcairn Islands': 'NZD',
 'Poland': 'PLN',
 'Portugal': 'EUR',
 'Puerto RicoÂ\xa0': 'USD',
 'Qatar': 'QAR',
 'ReunionÂ\xa0': 'EUR',
 'Romania': 'RON',
 'Russia': 'RUB',
 'Rwanda': 'RWF',
 'SabaÂ\xa0': 'USD',
 'Saint BarthelemyÂ\xa0': 'EUR',
 'Saint Helena': 'SHP',
 'Saint Kitts and Nevis': 'XCD',
 'Saint Lucia': 'XCD',
 'Saint MartinÂ\xa0': 'EUR',
 'Saint Pierre and Miquelon': 'EUR',
 'Saint Vincent and the Grenadines': 'XCD',
 'Samoa': 'WST',
 'San Marino': 'EUR',
 'Sao Tome and Principe': 'STN',
 'Saudi Arabia': 'SAR',
 'Senegal': 'XOF',
 'Serbia': 'RSD',
 'Seychelles': 'SCR',
 'Sierra Leone': 'SLE',
 'Singapore': 'SGD',
 'Sint Eustatius': 'USD',
 'Sint MaartenÂ\xa0': 'ANG',
 'Slovakia': 'EUR',
 'Slovenia': 'EUR',
 'Solomon Islands': 'SBD',
 'Somalia': 'SOS',
 'South Africa': 'ZAR',
 'South Georgia Island': 'GBP',
 'South Korea': 'KRW',
 'South Sudan': 'SSP',
 'Spain': 'EUR',
 'Sri Lanka': 'LKR',
 'Sudan': 'SDG',
 'Suriname': 'SRD',
 'Svalbard and Jan MayenÂ\xa0': 'NOK',
 'Sweden': 'SEK',
 'Switzerland': 'CHF',
 'Syria': 'SYP',
 'Taiwan': 'TWD',
 'Tajikistan': 'TJS',
 'Tanzania': 'TZS',
 'Thailand': 'THB',
 'Timor-Leste': 'USD',
 'Togo': 'XOF',
 'Tokelau': 'NZD',
 'Tonga': 'TOP',
 'Trinidad and Tobago': 'TTD',
 'Tristan da Cunha': 'GBP',
 'Tunisia': 'TND',
 'Turkey': 'TRY',
 'Turkmenistan': 'TMT',
 'Turks and Caicos IslandsÂ\xa0': 'USD',
 'Tuvalu': 'AUD',
 'Uganda': 'UGX',
 'Ukraine': 'UAH',
 'United Arab Emirates': 'AED',
 'United Kingdom': 'GBP',
 'United States': 'USD',
 'Uruguay': 'UYU',
 'US Virgin Islands': 'USD',
 'Uzbekistan': 'UZS',
 'Vanuatu': 'VUV',
 'Vatican City ': 'EUR',
 'Venezuela': 'VES',
 'Vietnam': 'VND',
 'Wake Island': 'USD',
 'Wallis and FutunaÂ\xa0': 'XPF',
 'Yemen': 'YER',
 'Zambia': 'ZMW',
 'Zimbabwe': 'USD'}

